[package]
name = "x86_encoding_ason"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ason = "0.2.0"
csv = "1.3.0"
serde = "1.0.202"
serde_derive = "1.0.202"
